# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Save command history
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
HISTSIZE=2000
SAVEHIST=1000

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# General aliases
alias r="ranger"
alias rf="rm -rf"
alias ls="lsd"
alias ll="ls -lh"
alias la="ls -ah"
alias lla="ls -lah"
alias lsa='ls -ld .*'
alias syn="sudo apt update -y && sudo apt upgrade -y"
alias install="sudo apt install"
alias xnet="curl ifconfig.me"
alias inet="sudo ifconfig | grep 'inet' | grep '192*' | awk '{print \$2}'"
alias c="protonvpn-cli c"
alias d="protonvpn-cli d"

alias gs="git status"
alias gi="git init"
alias ga="git add"
alias gc="git commit -m"
alias gcfl="git config -l"
alias gsh="git push"
alias gll="git pull"

# Configuration files aliases
alias zrc="vim ~/.zshrc"

# Personal aliases
alias dev="cd ~/dev"
alias bin="cd ~/dev/bin"

# ZSH plugings
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Powerlevel10k
source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
