# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Save command history
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
HISTSIZE=2000
SAVEHIST=1000


# General aliases
alias e="exit"
alias r="ranger"
alias rf="rm -rf"
alias ls="lsd"
alias ll="ls -lh"
alias lla="ls -lah"
alias la="ls -a"
alias lsa='ls -ld .*'
alias sync="apt update -y && sudo apt upgrade -y"
alias install="apt install"
alias xnet="curl ifconfig.me"
alias inet="ifconfig | grep 'inet' | grep '192*' | awk '{print \$2}'"
alias gs="git status"
alias gi="git init"
alias ga="git add"
alias gc="git commit -m"
alias gll="git pull"
alias gsh="git push"
alias gcfl="git config -l"


# Configuration files aliases
alias zrc="vim ~/.zshrc"

# Personal aliases
alias dev="cd ~/dev-lab && git pull"
alias bin="cd ~/dev-lab/bin"

# ZSH plugings
#source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Powerlevel10k
source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
